import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          " bg-background-950 min-h-screen text-text-100 px-6 py-1 flex items-center justify-center"
        }
      >
        {children}
      </body>
    </html>
  );
}
